cabal-version: 2.2
name:          ron-store-sqlite
version:       0
build-type:    Simple

library
  -- global
  build-depends:
    , base
    , monad-logger
    , selda
    , selda-sqlite
    , stm
    , tf-random
    , unliftio

  -- project
  build-depends:
    , ron
    , ron-rdt

  default-language:   GHC2021
  default-extensions:
    NoFieldSelectors
    StrictData

  exposed-modules:    RON.Store.Sqlite
