#!/usr/bin/env bash
set -eux -o pipefail

ghc_warnings=(
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
)
ghc_options=(${ghc_warnings[*]} -Werror)

packages=(
    ron
    ron-rdt
    ron-schema
    ron-storage
    ron-test
    # swarm
    examples
)

${STACK:-stack} test --ghc-options="${ghc_options[*]}"
