cabal-version: 2.2
name:          ron-tool
version:       0

executable ron
  -- global
  build-depends:
    , aeson
    , aeson-pretty
    , base
    , bytestring
    , containers
    , directory
    , optparse-applicative
    , text
    , yaml

  -- project
  build-depends:
    , ron
    , ron-rdt

  default-language:   GHC2021
  default-extensions:
    NoFieldSelectors
    StrictData

  main-is:            Main.hs
