cabal-version: 2.2
name:          editor-brick
version:       0
build-type:    Simple

common language
  build-depends:      base
  default-extensions:
    NoFieldSelectors
    StrictData

  default-language:   GHC2021
  ghc-options:        -threaded

executable demo-text-editor-brick
  import:         language

  -- global
  build-depends:
    , brick
    , text
    , text-zipper
    , vty

  -- project
  build-depends:
    , ron
    , ron-rdt
    , ron-storage

  hs-source-dirs: text-editor-brick
  main-is:        Main.hs
  other-modules:  Types
